/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReminderIndexRouteImport } from './routes/reminder.index'
import { Route as ReminderChannelsRouteImport } from './routes/reminder.channels'
import { Route as ReminderSettingsRouteImport } from './routes/reminder.settings'
import { Route as ReminderContactsIndexRouteImport } from './routes/reminder.contacts.index'
import { Route as ReminderContactsIdRouteImport } from './routes/reminder.contacts.$id'
import { Route as ReminderContactsNewRouteImport } from './routes/reminder.contacts.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderIndexRoute = ReminderIndexRouteImport.update({
  id: '/reminder/',
  path: '/reminder/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderChannelsRoute = ReminderChannelsRouteImport.update({
  id: '/reminder/channels',
  path: '/reminder/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderSettingsRoute = ReminderSettingsRouteImport.update({
  id: '/reminder/settings',
  path: '/reminder/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderContactsIndexRoute = ReminderContactsIndexRouteImport.update({
  id: '/reminder/contacts/',
  path: '/reminder/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderContactsIdRoute = ReminderContactsIdRouteImport.update({
  id: '/reminder/contacts/$id',
  path: '/reminder/contacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderContactsNewRoute = ReminderContactsNewRouteImport.update({
  id: '/reminder/contacts/new',
  path: '/reminder/contacts/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reminder/channels': typeof ReminderChannelsRoute
  '/reminder/settings': typeof ReminderSettingsRoute
  '/reminder/': typeof ReminderIndexRoute
  '/reminder/contacts/$id': typeof ReminderContactsIdRoute
  '/reminder/contacts/new': typeof ReminderContactsNewRoute
  '/reminder/contacts/': typeof ReminderContactsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reminder/channels': typeof ReminderChannelsRoute
  '/reminder/settings': typeof ReminderSettingsRoute
  '/reminder': typeof ReminderIndexRoute
  '/reminder/contacts/$id': typeof ReminderContactsIdRoute
  '/reminder/contacts/new': typeof ReminderContactsNewRoute
  '/reminder/contacts': typeof ReminderContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reminder/channels': typeof ReminderChannelsRoute
  '/reminder/settings': typeof ReminderSettingsRoute
  '/reminder/': typeof ReminderIndexRoute
  '/reminder/contacts/$id': typeof ReminderContactsIdRoute
  '/reminder/contacts/new': typeof ReminderContactsNewRoute
  '/reminder/contacts/': typeof ReminderContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reminder/channels'
    | '/reminder/settings'
    | '/reminder/'
    | '/reminder/contacts/$id'
    | '/reminder/contacts/new'
    | '/reminder/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reminder/channels'
    | '/reminder/settings'
    | '/reminder'
    | '/reminder/contacts/$id'
    | '/reminder/contacts/new'
    | '/reminder/contacts'
  id:
    | '__root__'
    | '/'
    | '/reminder/channels'
    | '/reminder/settings'
    | '/reminder/'
    | '/reminder/contacts/$id'
    | '/reminder/contacts/new'
    | '/reminder/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReminderChannelsRoute: typeof ReminderChannelsRoute
  ReminderSettingsRoute: typeof ReminderSettingsRoute
  ReminderIndexRoute: typeof ReminderIndexRoute
  ReminderContactsIdRoute: typeof ReminderContactsIdRoute
  ReminderContactsNewRoute: typeof ReminderContactsNewRoute
  ReminderContactsIndexRoute: typeof ReminderContactsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder/': {
      id: '/reminder/'
      path: '/reminder'
      fullPath: '/reminder/'
      preLoaderRoute: typeof ReminderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder/channels': {
      id: '/reminder/channels'
      path: '/reminder/channels'
      fullPath: '/reminder/channels'
      preLoaderRoute: typeof ReminderChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder/settings': {
      id: '/reminder/settings'
      path: '/reminder/settings'
      fullPath: '/reminder/settings'
      preLoaderRoute: typeof ReminderSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder/contacts/': {
      id: '/reminder/contacts/'
      path: '/reminder/contacts'
      fullPath: '/reminder/contacts/'
      preLoaderRoute: typeof ReminderContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder/contacts/$id': {
      id: '/reminder/contacts/$id'
      path: '/reminder/contacts/$id'
      fullPath: '/reminder/contacts/$id'
      preLoaderRoute: typeof ReminderContactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder/contacts/new': {
      id: '/reminder/contacts/new'
      path: '/reminder/contacts/new'
      fullPath: '/reminder/contacts/new'
      preLoaderRoute: typeof ReminderContactsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReminderChannelsRoute: ReminderChannelsRoute,
  ReminderSettingsRoute: ReminderSettingsRoute,
  ReminderIndexRoute: ReminderIndexRoute,
  ReminderContactsIdRoute: ReminderContactsIdRoute,
  ReminderContactsNewRoute: ReminderContactsNewRoute,
  ReminderContactsIndexRoute: ReminderContactsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
